### ISSUE TITLE
Command touch() returns an error when result TOUCHED shall be OK

### ISSUE THREAD

**Issue by christian-lefty** [iFaceless/beanstalkc-rust#2]
Hello, I believe the response "TOUCHED" shall be considered a success for the touch() command?

https://github.com/iFaceless/beanstalkc-rust/blob/1152b67e427514ee10c41c2498bad4ff8ab1e6b6/src/command.rs#L377

**Comment by iFaceless** [comment]
:) Thanks a lot. Got fixed [here](https://github.com/iFaceless/beanstalkc-rust/pull/3/files).
